package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'releng_dobson_50_4_bc_cc_cm_pc_AssemblyLine_VersionUpdate'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("releng_dobson_50_4_bc_cc_cm_pc_AssemblyLine_VersionUpdate")) {
    check(paused == false) {
        "Unexpected paused: '$paused'"
    }
    paused = true
}
