package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'TestSubproject_TestSubprojectBuildconfiguration'
in the project with id = 'TestSubproject', and delete the patch script.
*/
create(RelativeId("TestSubproject"), BuildType({
    id("TestSubproject_TestSubprojectBuildconfiguration")
    name = "test_subproject_buildconfiguration"
}))

